Change the path of require module
The same problem as issue183, if not change the path

$ nodejs index.js 
/3Dev/Projects/TelinkAutoTest/SocketIO/socket.io/examples/chat/index.js:7
Var io = require ('socket.io') (server);
    ^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3